-- Migration 007: Seed data
-- Goods catalog, recipes, districts, system ledger accounts.
-- All prices in INTEGER CENTS (1 BCE = 100 cents).

-- ============================================================
-- GOODS  (the minimal essential + non-essential set)
-- ============================================================
INSERT INTO goods (code, name, is_essential) VALUES
    ('RAW_FOOD',              'Raw Food',              TRUE),
    ('PROCESSED_FOOD',        'Processed Food',        TRUE),
    ('FRESH_WATER',           'Fresh Water',            TRUE),
    ('ENERGY',                'Energy (Utility)',       TRUE),
    ('MATERIALS',             'Materials',              FALSE),
    ('BUILDING_MATERIALS',    'Building Materials',     FALSE),
    ('INDUSTRIAL_MACHINERY',  'Industrial Machinery',   FALSE),
    ('ENTERTAINMENT',         'Entertainment',          FALSE),
    ('WASTE',                 'Waste',                  FALSE)   -- sink good from production
ON CONFLICT (code) DO NOTHING;

-- ============================================================
-- RECIPES
-- ============================================================

-- Processed Food:
--   inputs:  RawFood x3, Water x1, Energy x1
--   outputs: ProcessedFood x5, Waste x1
--   duration: 3600s (1 game-hour)
INSERT INTO recipes (code, name, duration_seconds) VALUES
    ('PROCESS_FOOD',       'Processed Food Production', 3600),
    ('BUILD_MATERIALS',    'Building Materials Production', 7200);

-- Wire up inputs/outputs using subqueries to resolve IDs
-- (goods IDs are auto-generated by smallserial)

-- PROCESS_FOOD inputs
INSERT INTO recipe_inputs (recipe_id, good_id, qty)
SELECT r.id, g.id, v.qty
FROM (VALUES
    ('RAW_FOOD',    3.0),
    ('FRESH_WATER', 1.0),
    ('ENERGY',      1.0)
) AS v(code, qty)
JOIN recipes r ON r.code = 'PROCESS_FOOD'
JOIN goods   g ON g.code = v.code;

-- PROCESS_FOOD outputs
INSERT INTO recipe_outputs (recipe_id, good_id, qty)
SELECT r.id, g.id, v.qty
FROM (VALUES
    ('PROCESSED_FOOD', 5.0),
    ('WASTE',          1.0)
) AS v(code, qty)
JOIN recipes r ON r.code = 'PROCESS_FOOD'
JOIN goods   g ON g.code = v.code;

-- BUILD_MATERIALS inputs
INSERT INTO recipe_inputs (recipe_id, good_id, qty)
SELECT r.id, g.id, v.qty
FROM (VALUES
    ('MATERIALS', 2.0),
    ('ENERGY',    2.0)
) AS v(code, qty)
JOIN recipes r ON r.code = 'BUILD_MATERIALS'
JOIN goods   g ON g.code = v.code;

-- BUILD_MATERIALS outputs
INSERT INTO recipe_outputs (recipe_id, good_id, qty)
SELECT r.id, g.id, v.qty
FROM (VALUES
    ('BUILDING_MATERIALS', 3.0)
) AS v(code, qty)
JOIN recipes r ON r.code = 'BUILD_MATERIALS'
JOIN goods   g ON g.code = v.code;

-- ============================================================
-- DISTRICTS  (12 districts with pricing modifiers)
-- ============================================================
INSERT INTO districts (code, name, pricing_modifier) VALUES
    ('CBD',         'Central Business District',  1.50),
    ('OLD_TOWN',    'Old Town',                   1.20),
    ('MARINA',      'Marina Waterfront',          1.40),
    ('TECH_PARK',   'Technology Park',             1.30),
    ('MARKET_SQ',   'Market Square',              1.00),
    ('INDUSTRIAL',  'Industrial Zone',             0.80),
    ('HARBOR',      'Harbor District',             0.90),
    ('UNIVERSITY',  'University Quarter',          1.10),
    ('SUBURBS_N',   'North Suburbs',              0.85),
    ('SUBURBS_S',   'South Suburbs',              0.85),
    ('ENTERTAINMENT','Entertainment Strip',        1.25),
    ('OUTSKIRTS',   'City Outskirts',             0.70)
ON CONFLICT (code) DO NOTHING;

-- ============================================================
-- NPC_MARKET_STATE  (initial reference prices for all goods)
-- ============================================================
INSERT INTO npc_market_state (good_id, demand, supply, ref_price_cents, last_6h_ref_price_cents)
SELECT g.id, v.demand, v.supply, v.price, v.price
FROM (VALUES
    ('RAW_FOOD',             1000.0, 1000.0, 200),
    ('PROCESSED_FOOD',       800.0,  600.0,  500),
    ('FRESH_WATER',          1200.0, 1200.0, 100),
    ('ENERGY',               900.0,  900.0,  300),
    ('MATERIALS',            400.0,  400.0,  800),
    ('BUILDING_MATERIALS',   200.0,  150.0,  1500),
    ('INDUSTRIAL_MACHINERY', 50.0,   40.0,   50000),
    ('ENTERTAINMENT',        600.0,  500.0,  1000),
    ('WASTE',                100.0,  500.0,  10)
) AS v(code, demand, supply, price)
JOIN goods g ON g.code = v.code;

-- ============================================================
-- SYSTEM LEDGER ACCOUNTS
-- These are the "other side" of double-entry for sources/sinks.
-- owner_type = 'system', owner_id = NULL, identified by convention.
-- ============================================================
INSERT INTO ledger_accounts (owner_type, owner_id, currency) VALUES
    ('system', NULL, 'BCE'),  -- id=1: Job Payroll Source (money creation)
    ('system', NULL, 'BCE'),  -- id=2: Tax Sink (money destruction)
    ('system', NULL, 'BCE'),  -- id=3: Market Escrow (holds money during trades)
    ('system', NULL, 'BCE'),  -- id=4: Bill Payment Sink
    ('system', NULL, 'BCE'),  -- id=5: NPC Vendor Account
    ('system', NULL, 'BCE');  -- id=6: Initial Grant Source (new player starting money)
